# Generated by Django 2.0.3 on 2018-08-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzacrust',
            name='topping_cost_factor',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
